apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-2
  namespace: argocd
spec:
  destination:
    namespace: hello-2
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/sikalabs/charts.git
    targetRevision: HEAD
    path: charts/hello-world
    helm:
      values: |
        image: sikalabs/hello-world-server:cra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
