apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-hooks
  namespace: argocd
spec:
  destination:
    namespace: sync-hook
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/argocd-training/examples.git
    path: sync-hooks
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
